version: "3.3" # specify docker-compose version

# Define the services/containers to be run
services:
  # express: #name of the second service
  #   build: # specify the directory of the Dockerfile
  #     context: .
  #     dockerfile: dockerfile
  #   container_name: mean_angular_express
  #   ports:
  #     - "3000:3000" #specify ports forewarding
  #     # Below database enviornment variable for api is helpful when you have to use database as managed service
  #   environment:
  #     - SECRET=Thisismysecret
  #     - MONGO_DB_USERNAME=admin-user
  #     - MONGO_DB_PASSWORD=admin-password
  #     - MONGO_DB_HOST=database
  #     - MONGO_DB_PORT=
  #     - MONGO_DB_PARAMETERS=?authSource=admin
  #     - MONGO_DB_DATABASE=mean-contacts
  #   links:
  #     - database

  database: # name of service: database
    image: mongo:latest # specify image to build container from
    container_name: mean_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mean-ecommerce
    volumes:
      - ./mongo:/home/mongodb
      - ./docker/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    ports:
      - "27017:27017" # specify port forewarding

